### ISSUE TITLE
Problem with the plugin 

### ISSUE THREAD

**Issue by ambitious-octopus** [ironblaster/mock_turtle#1]
**Describe the bug**
The plugin seems to raise this error:
```
cheshire_cat_core           | [2023-11-11 08:34:59.160] ERROR  cat.mad_hatter.mad_hatter.MadHatter.execute_hook::287 => 'Error in plugin mock_turtle::before_cat_recalls_declarative_memories'
cheshire_cat_core           | [2023-11-11 08:34:59.165] ERROR  cat.mad_hatter.mad_hatter.MadHatter.execute_hook::288 => KeyError('threshold_declarative_memories')
cheshire_cat_core           | Traceback (most recent call last):
cheshire_cat_core           |   File "/app/cat/mad_hatter/mad_hatter.py", line 278, in execute_hook
cheshire_cat_core           |     tea_spoon = hook.function(
cheshire_cat_core           |   File "/app/cat/plugins/mock_turtle/mock_turtle.py", line 27, in before_cat_recalls_declarative_memories
cheshire_cat_core           |     config["threshold"] = setting["threshold_declarative_memories"]
cheshire_cat_core           | KeyError: 'threshold_declarative_memories'
```
And the conversation does not respect my memories. 
**To Reproduce**
I have a limited number of memories: (32 declarative, 10 episodic) and I am using OpenAI Chagpt and OpenAi embedder.

**Comment by andrea-rinoldi** [comment]
I'm having the same problem, Thanks
